2021-09-27 22:00:51,407 ERROR: Exception on /login [GET] [in E:\Repos\personal\Flask Mega Tutorial\venv\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "E:\Repos\personal\Flask Mega Tutorial\venv\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\Repos\personal\Flask Mega Tutorial\venv\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\Repos\personal\Flask Mega Tutorial\venv\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\Repos\personal\Flask Mega Tutorial\venv\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "E:\Repos\personal\Flask Mega Tutorial\microblog\app\routes.py", line 45, in login
    return render_template('login.html', title='Sign In', form=form)
  File "E:\Repos\personal\Flask Mega Tutorial\venv\lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(
  File "E:\Repos\personal\Flask Mega Tutorial\venv\lib\site-packages\flask\templating.py", line 128, in _render
    rv = template.render(context)
  File "E:\Repos\personal\Flask Mega Tutorial\venv\lib\site-packages\jinja2\environment.py", line 1304, in render
    self.environment.handle_exception()
  File "E:\Repos\personal\Flask Mega Tutorial\venv\lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "E:\Repos\personal\Flask Mega Tutorial\microblog\app\templates\login.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "E:\Repos\personal\Flask Mega Tutorial\venv\lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "E:\Repos\personal\Flask Mega Tutorial\microblog\app\templates\base.html", line 55, in template
    {{% endblock %}}
jinja2.exceptions.TemplateSyntaxError: unexpected '%'
2021-09-27 22:01:17,031 INFO: Microblog startup [in E:\Repos\personal\Flask Mega Tutorial\microblog\app\__init__.py:45]
