2021-09-27 22:00:51,407 ERROR: Exception on /login [GET] [in E:\Repos\personal\Flask Mega Tutorial\venv\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "E:\Repos\personal\Flask Mega Tutorial\venv\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\Repos\personal\Flask Mega Tutorial\venv\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\Repos\personal\Flask Mega Tutorial\venv\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\Repos\personal\Flask Mega Tutorial\venv\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "E:\Repos\personal\Flask Mega Tutorial\microblog\app\routes.py", line 45, in login
    return render_template('login.html', title='Sign In', form=form)
  File "E:\Repos\personal\Flask Mega Tutorial\venv\lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(
  File "E:\Repos\personal\Flask Mega Tutorial\venv\lib\site-packages\flask\templating.py", line 128, in _render
    rv = template.render(context)
  File "E:\Repos\personal\Flask Mega Tutorial\venv\lib\site-packages\jinja2\environment.py", line 1304, in render
    self.environment.handle_exception()
  File "E:\Repos\personal\Flask Mega Tutorial\venv\lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "E:\Repos\personal\Flask Mega Tutorial\microblog\app\templates\login.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "E:\Repos\personal\Flask Mega Tutorial\venv\lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "E:\Repos\personal\Flask Mega Tutorial\microblog\app\templates\base.html", line 55, in template
    {{% endblock %}}
jinja2.exceptions.TemplateSyntaxError: unexpected '%'
2021-09-27 22:01:17,031 INFO: Microblog startup [in E:\Repos\personal\Flask Mega Tutorial\microblog\app\__init__.py:45]
2021-09-27 22:42:07,175 INFO: Microblog startup [in E:\Repos\personal\Flask Mega Tutorial\microblog\app\__init__.py:47]
2021-09-27 22:42:21,084 INFO: Microblog startup [in E:\Repos\personal\Flask Mega Tutorial\microblog\app\__init__.py:47]
2021-09-27 22:42:50,295 INFO: Microblog startup [in E:\Repos\personal\Flask Mega Tutorial\microblog\app\__init__.py:47]
2021-09-27 22:43:11,274 INFO: Microblog startup [in E:\Repos\personal\Flask Mega Tutorial\microblog\app\__init__.py:47]
2021-09-27 22:43:20,082 INFO: Microblog startup [in E:\Repos\personal\Flask Mega Tutorial\microblog\app\__init__.py:47]
2021-09-27 22:44:24,178 INFO: Microblog startup [in E:\Repos\personal\Flask Mega Tutorial\microblog\app\__init__.py:47]
2021-09-27 22:44:43,650 INFO: Microblog startup [in E:\Repos\personal\Flask Mega Tutorial\microblog\app\__init__.py:47]
2021-09-27 22:44:44,788 ERROR: Exception on /explore [GET] [in E:\Repos\personal\Flask Mega Tutorial\venv\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "E:\Repos\personal\Flask Mega Tutorial\venv\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\Repos\personal\Flask Mega Tutorial\venv\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\Repos\personal\Flask Mega Tutorial\venv\lib\site-packages\flask\app.py", line 1511, in full_dispatch_request
    rv = self.preprocess_request()
  File "E:\Repos\personal\Flask Mega Tutorial\venv\lib\site-packages\flask\app.py", line 1857, in preprocess_request
    rv = self.ensure_sync(func)()
  File "E:\Repos\personal\Flask Mega Tutorial\microblog\app\routes.py", line 89, in before_request
    g.locale = str(get_locale())
  File "E:\Repos\personal\Flask Mega Tutorial\venv\lib\site-packages\flask_babel\__init__.py", line 226, in get_locale
    rv = babel.locale_selector_func()
  File "E:\Repos\personal\Flask Mega Tutorial\microblog\app\__init__.py", line 51, in get_locale
    return request.accept_langugaes.best_match(app.config['LANGUAGES'])
AttributeError: 'Request' object has no attribute 'accept_langugaes'
2021-09-27 22:44:45,852 ERROR: Exception on /explore [GET] [in E:\Repos\personal\Flask Mega Tutorial\venv\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "E:\Repos\personal\Flask Mega Tutorial\venv\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\Repos\personal\Flask Mega Tutorial\venv\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\Repos\personal\Flask Mega Tutorial\venv\lib\site-packages\flask\app.py", line 1511, in full_dispatch_request
    rv = self.preprocess_request()
  File "E:\Repos\personal\Flask Mega Tutorial\venv\lib\site-packages\flask\app.py", line 1857, in preprocess_request
    rv = self.ensure_sync(func)()
  File "E:\Repos\personal\Flask Mega Tutorial\microblog\app\routes.py", line 89, in before_request
    g.locale = str(get_locale())
  File "E:\Repos\personal\Flask Mega Tutorial\venv\lib\site-packages\flask_babel\__init__.py", line 226, in get_locale
    rv = babel.locale_selector_func()
  File "E:\Repos\personal\Flask Mega Tutorial\microblog\app\__init__.py", line 51, in get_locale
    return request.accept_langugaes.best_match(app.config['LANGUAGES'])
AttributeError: 'Request' object has no attribute 'accept_langugaes'
2021-09-27 22:44:47,084 ERROR: Exception on /explore [GET] [in E:\Repos\personal\Flask Mega Tutorial\venv\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "E:\Repos\personal\Flask Mega Tutorial\venv\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\Repos\personal\Flask Mega Tutorial\venv\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\Repos\personal\Flask Mega Tutorial\venv\lib\site-packages\flask\app.py", line 1511, in full_dispatch_request
    rv = self.preprocess_request()
  File "E:\Repos\personal\Flask Mega Tutorial\venv\lib\site-packages\flask\app.py", line 1857, in preprocess_request
    rv = self.ensure_sync(func)()
  File "E:\Repos\personal\Flask Mega Tutorial\microblog\app\routes.py", line 89, in before_request
    g.locale = str(get_locale())
  File "E:\Repos\personal\Flask Mega Tutorial\venv\lib\site-packages\flask_babel\__init__.py", line 226, in get_locale
    rv = babel.locale_selector_func()
  File "E:\Repos\personal\Flask Mega Tutorial\microblog\app\__init__.py", line 51, in get_locale
    return request.accept_langugaes.best_match(app.config['LANGUAGES'])
AttributeError: 'Request' object has no attribute 'accept_langugaes'
2021-09-27 22:45:02,396 ERROR: Exception on /explore [GET] [in E:\Repos\personal\Flask Mega Tutorial\venv\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "E:\Repos\personal\Flask Mega Tutorial\venv\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\Repos\personal\Flask Mega Tutorial\venv\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\Repos\personal\Flask Mega Tutorial\venv\lib\site-packages\flask\app.py", line 1511, in full_dispatch_request
    rv = self.preprocess_request()
  File "E:\Repos\personal\Flask Mega Tutorial\venv\lib\site-packages\flask\app.py", line 1857, in preprocess_request
    rv = self.ensure_sync(func)()
  File "E:\Repos\personal\Flask Mega Tutorial\microblog\app\routes.py", line 89, in before_request
    g.locale = str(get_locale())
  File "E:\Repos\personal\Flask Mega Tutorial\venv\lib\site-packages\flask_babel\__init__.py", line 226, in get_locale
    rv = babel.locale_selector_func()
  File "E:\Repos\personal\Flask Mega Tutorial\microblog\app\__init__.py", line 51, in get_locale
    return request.accept_languages.best_match(app.config['LANGUAGES'])
AttributeError: 'Request' object has no attribute 'accept_langugaes'
2021-09-27 22:45:08,476 INFO: Microblog startup [in E:\Repos\personal\Flask Mega Tutorial\microblog\app\__init__.py:47]
2021-09-28 19:51:46,244 INFO: Microblog startup [in E:\Repos\personal\Flask Mega Tutorial\microblog\app\__init__.py:47]
2021-09-28 19:51:58,332 INFO: Microblog startup [in E:\Repos\personal\Flask Mega Tutorial\microblog\app\__init__.py:47]
2021-09-28 20:09:58,955 INFO: Microblog startup [in E:\Repos\personal\Flask Mega Tutorial\microblog\app\__init__.py:47]
2021-09-28 20:10:05,820 INFO: Microblog startup [in E:\Repos\personal\Flask Mega Tutorial\microblog\app\__init__.py:47]
2021-09-28 20:31:45,236 INFO: Microblog startup [in E:\Repos\personal\Flask Mega Tutorial\microblog\app\__init__.py:47]
2021-09-28 20:34:01,932 INFO: Microblog startup [in E:\Repos\personal\Flask Mega Tutorial\microblog\app\__init__.py:47]
2021-09-28 20:34:31,421 INFO: Microblog startup [in E:\Repos\personal\Flask Mega Tutorial\microblog\app\__init__.py:47]
2021-09-28 20:42:24,326 INFO: Microblog startup [in E:\Repos\personal\Flask Mega Tutorial\microblog\app\__init__.py:47]
2021-09-28 20:44:30,760 INFO: Microblog startup [in E:\Repos\personal\Flask Mega Tutorial\microblog\app\__init__.py:47]
2021-09-28 20:44:39,590 INFO: Microblog startup [in E:\Repos\personal\Flask Mega Tutorial\microblog\app\__init__.py:47]
